#!/bin/bash

# seyren - Startup script for seyren

# chkconfig: 35 85 15
# description: Seyren - Graphite Alerting Tool
# processname: seyren
# config /usr/local/seyren-master
# pidfile: /usr/local/seyren-master/seyren.pid

. /etc/rc.d/init.d/functions

## Environment Variables -- Fill in your Environment Variables GRAPHITE_URL/SMTPHOST/SMTPPORT
hostname=`hostname`

GRAPHITE_URL=""
export GRAPHITE_URL

SMTP_HOST=""
export SMTP_HOST

SMTP_PORT=""
export SMTP_PORT

SEYREN_URL="http://$hostname:8080/seyren"
export SEYREN_URL

PIDGET=$(ps -ef | grep java | grep -v grep | awk '{print $2}')

# Seyren Daemon - Enter your Java location and seyren-master install directories - Amend the log directory if needed

seyrend=${SEYREND- ADDJAVADIRHERE -jar ADDSEYRENMASTERHERE/seyren-web/target/dependency/jetty-runner.jar --path /seyren ADDSEYRENMASTERHERE/seyren-web/target/*.war > /dev/null 2>&1 >> /var/log/seyren/seyren.output.log 2>> /var/log/seyren/seyren.log  &}

SEYREN_USER=seyren
SEYREN_GROUP=seyren

start()
{
  echo -n $"Starting seyren: "
  daemon --user "$SEYREN_USER" $seyrend
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/seyrend
}

stop()
{
  echo -n $"Stopping seyren: "
  kill -9 $PIDGET 0
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/seyrend
}

restart () {
        stop
        start
}

ulimit -n 12000
RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f /var/lock/subsys/seyrend ] && restart || :
    ;;
  status)
    status $seyrend
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL
